"""wirtschaftsplan

Revision ID: 0b2add809501
Revises: 50dc58878cdf
Create Date: 2026-09-01 19:02:15.150521

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0b2add809501'
down_revision: str | Sequence[str] | None = '50dc58878cdf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('month_index', sa.Integer(), nullable=False),
    sa.Column('cost_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cost_type_id'], ['cost_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['billing_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'month_index', 'cost_type_id', name='uq_budget_cell')
    )
    with op.batch_alter_table('budget_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_entries_cost_type_id'), ['cost_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_entries_period_id'), ['period_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_entries_period_id'))
        batch_op.drop_index(batch_op.f('ix_budget_entries_cost_type_id'))

    op.drop_table('budget_entries')
    # ### end Alembic commands ###
