"""csv import

Revision ID: 50dc58878cdf
Revises: f5b2ccfd55a5
Create Date: 2026-08-31 14:07:33.435951

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '50dc58878cdf'
down_revision: str | Sequence[str] | None = 'f5b2ccfd55a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('delimiter', sa.String(length=4), nullable=False),
    sa.Column('encoding', sa.String(length=20), nullable=False),
    sa.Column('decimal_comma', sa.Boolean(), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('header_row', sa.Integer(), nullable=False),
    sa.Column('amount_mode', sa.String(length=20), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_profiles_signature'), ['signature'], unique=True)

    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('raw_content', sa.LargeBinary(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ENTWURF', 'IMPORTIERT', 'VERWORFEN', name='importbatchstatus', native_enum=False, length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['import_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_account_id'), ['account_id'], unique=False)

    op.create_table('import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('payee', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=1000), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('parse_error', sa.String(length=500), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('include', sa.Boolean(), nullable=False),
    sa.Column('cost_type_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('suggestion_note', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cost_type_id'], ['cost_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_rows_batch_id'), ['batch_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.Enum('MANUAL', 'CSV_IMPORT', name='transactionsource', native_enum=False, length=16), server_default='manuell', nullable=False))
        batch_op.add_column(sa.Column('import_row_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_import_row_id'), ['import_row_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_transactions_import_row_id', 'import_rows', ['import_row_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_import_row_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_import_row_id'))
        batch_op.drop_column('import_row_id')
        batch_op.drop_column('source')

    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_rows_batch_id'))

    op.drop_table('import_rows')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_account_id'))

    op.drop_table('import_batches')
    with op.batch_alter_table('import_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_profiles_signature'))

    op.drop_table('import_profiles')
    # ### end Alembic commands ###
