"""abschlag_flag_inflation

Revision ID: 5fd0b12998a5
Revises: 0b2add809501
Create Date: 2026-09-04 10:58:29.477377

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5fd0b12998a5'
down_revision: str | Sequence[str] | None = '0b2add809501'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compute_next_advance', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('inflation_rate', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_periods', schema=None) as batch_op:
        batch_op.drop_column('inflation_rate')
        batch_op.drop_column('compute_next_advance')

    # ### end Alembic commands ###
