"""initial schema

Revision ID: f5b2ccfd55a5
Revises: 
Create Date: 2026-08-31 12:55:47.432650

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f5b2ccfd55a5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('GIRO', 'RUECKLAGE', name='accounttype', native_enum=False, length=16), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('opening_balance_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('billing_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINAL', name='periodstatus', native_enum=False, length=10), nullable=False),
    sa.Column('reserve_opening_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('HEIZEN_WASSER_BETRIEB', 'VERSICHERUNGEN', 'GEBUEHREN_ABGABEN', 'WARTUNG_DIENSTLEISTUNG', 'VERWALTUNG', 'SONSTIGES', name='costcategory', native_enum=False, length=32), nullable=False),
    sa.Column('default_supplier', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('BETRIEBSKOSTEN', 'HAUSGELD', 'ERSTATTUNG', 'RUECKLAGE', 'SONDERUMLAGE', 'INVESTITION', name='costkind', native_enum=False, length=20), nullable=False),
    sa.Column('allocation_strategy', sa.Enum('MEA', 'ZAEHLER', 'VORAUSZAHLUNG', 'PROPORTIONAL', name='allocationstrategy', native_enum=False, length=20), nullable=False),
    sa.Column('proportional_to_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proportional_to_id'], ['cost_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_types_name'), ['name'], unique=True)

    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('mea', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owners_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('allocation_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('cost_type_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cost_type_id'], ['cost_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['billing_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'cost_type_id', 'owner_id', name='uq_override_period_ct_owner')
    )
    with op.batch_alter_table('allocation_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocation_overrides_cost_type_id'), ['cost_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allocation_overrides_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allocation_overrides_period_id'), ['period_id'], unique=False)

    op.create_table('period_opening_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('hausgeld_carryover', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['billing_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'owner_id', name='uq_opening_period_owner')
    )
    with op.batch_alter_table('period_opening_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_period_opening_balances_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_period_opening_balances_period_id'), ['period_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('payee', sa.String(length=200), nullable=False),
    sa.Column('cost_type_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cost_type_id'], ['cost_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_booking_date'), ['booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_cost_type_id'), ['cost_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_owner_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_cost_type_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_booking_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('period_opening_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_period_opening_balances_period_id'))
        batch_op.drop_index(batch_op.f('ix_period_opening_balances_owner_id'))

    op.drop_table('period_opening_balances')
    with op.batch_alter_table('allocation_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocation_overrides_period_id'))
        batch_op.drop_index(batch_op.f('ix_allocation_overrides_owner_id'))
        batch_op.drop_index(batch_op.f('ix_allocation_overrides_cost_type_id'))

    op.drop_table('allocation_overrides')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owners_code'))

    op.drop_table('owners')
    with op.batch_alter_table('cost_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_types_name'))

    op.drop_table('cost_types')
    op.drop_table('billing_periods')
    op.drop_table('accounts')
    # ### end Alembic commands ###
